# Generated by Django 3.0.4 on 2020-03-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='search_country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
